export const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_FAILURE = 'FETCH_COUNTRY_FAILURE';
export const FETCH_COUNTRY_GDP_REQUEST = 'FETCH_COUNTRY_GDP__REQUEST';
export const FETCH_COUNTRY_GDP_SUCCESS = 'FETCH_COUNTRY_GDP_SUCCESS';
export const FETCH_COUNTRY_GDP_END = 'FETCH_COUNTRY_GDP_END';
export const FETCH_COUNTRY_GDP_FAILURE = 'FETCH_COUNTRY_GDP_FAILURE';
export const SET_COUNTRY_GDP = 'SET_COUNTRY_GDP';

export const FETCH_CYCLIST_REQUEST = 'FETCH_CYCLIST_REQUEST';
export const FETCH_CYCLIST_SUCCESS = 'FETCH_CYCLIST_SUCCESS';
export const FETCH_CYCLIST_ERROR = 'FETCH_CYCLIST_ERROR';

export const FETCH_TEMPRATURE_REQUEST = 'FETCH_TEMPRATURE_REQUEST';
export const FETCH_TEMPRATURE_SUCCESS = 'FETCH_TEMPRATURE_SUCCESS';
export const FETCH_TEMPRATURE_ERROR = 'FETCH_TEMPRATURE_ERROR';
export const SET_COUNTRY_TEMEPRATURE = 'SET_COUNTRY_TEMEPRATURE';

export const FETCH_COUNTRIES_SHARE_BORDER_REQUEST = 'FETCH_COUNTRIES_SHARE_BORDER_REQUEST';
export const FETCH_COUNTRIES_SHARE_BORDER_SUCCESS = 'FETCH_COUNTRIES_SHARE_BORDER_SUCCESS';
export const FETCH_COUNTRIES_SHARE_BORDER_ERROR = 'FETCH_COUNTRIES_SHARE_BORDER_ERROR';


export const FETCH_WOLRDMAP_JSON_PATH_REQUEST = 'FETCH_WOLRDMAP_JSON_PATH_REQUEST';
export const FETCH_WOLRDMAP_JSON_PATH_SUCCESS = 'FETCH_WOLRDMAP_JSON_PATH_SUCCESS';
export const FETCH_WOLRDMAP_JSON_PATH_ERROR = 'FETCH_WOLRDMAP_JSON_PATH_ERROR';

//METEORITE-strike-data
export const FETCH_METEORITE_JSON_PATH_REQUEST = 'FETCH_METEORITE_JSON_PATH_REQUEST';
export const FETCH_METEORITE_JSON_PATH_SUCCESS = 'FETCH_METEORITE_JSON_PATH_SUCCESS';
export const FETCH_METEORITE_JSON_PATH_ERROR = 'FETCH_METEORITE_JSON_PATH_ERROR';


export const svg_dimensions_gdp = {
    margin : {top: 50, right: 100, bottom: 80, left: 100},
    width :960,
    height : 500,
}

export const svg_dimensions_cyclist = {
    margin : {top: 20, right: 30, bottom: 70, left: 70},
    width :960,
    height : 500,
}

export const svg_dimensions = {
    margin : {top: 20, right: 30, bottom: 40, left: 80},
    width :960,
    height : 500,
}


export const svg_dimensions_climat = {
    margin : {top: 5, right: 10, bottom: 60, left: 90},
    width :960,
    height : 500,
}

export const intervalDateGdp = {
    start:'1960',
    end:'2017'
};
